### ISSUE TITLE
mcr.microsoft.com is frequently not available ` unexpected status code: 503 Service Unavailable`

### ISSUE THREAD

**Issue by samcarton** [microsoft/containerregistry#179]
Similar to #169 - we are seeing this error happening very frequently in our CICD pipeline over the last ~week.

We are using github action `docker/build-push-action@v6` and the error message is:

```
ERROR: failed to solve: failed to compute cache key: failed to copy: httpReadSeeker: failed open: unexpected status code https://mcr.microsoft.com/v2/dotnet/sdk/blobs/sha256:30ea495b602b5919488ec57d1f5fbaaa46fafc6a805176fe7b562cce482d4dbf: 503 Service Unavailable
```

**Comment by rowanmoul** [comment]
We also get these intermittently in GitHub Actions. We recently switched to actions from azure pipelines. This was never an issue in azure pipelines. I presume that traffic from GitHub Actions are not treated the same as traffic from inside the azure network? If so, perhaps you could consider creating a GitHub Container Registry mirror for MCR, similar to how you push to Docker Hub?

**Comment by jwtty** [comment]
Same issue here: we are getting very frequent 503 issue in our github actions these days: 
```
#8 ERROR: failed to copy: httpReadSeeker: failed open: unexpected status code https://mcr.microsoft.com/v2/oss/go/microsoft/golang/blobs/sha256:5b738f5214541552f723579fda5b0260a8e95758e7b5d3e08f8cf4fd9034577c: 503 Service Unavailable
```

**Comment by terencet-dev** [comment]
Looking into this with our engineering team

**Comment by northtyphoon** [comment]
We have deployed an update to mitigate the 503 issue. Please let us know if you see things improve on your end.

**Comment by CamDHall** [comment]
We are still seeing this issue. 

`failed to solve: mcr.microsoft.com/dotnet/sdk:8.0: failed to resolve source metadata for mcr.microsoft.com/dotnet/sdk:8.0: failed to do request: Head "https://mcr.microsoft.com/v2/dotnet/sdk/manifests/8.0": EOF`

**Comment by rowanmoul** [comment]
@CamDHall The EOF issue, while simlar, is tracked in #180, which is probably not related to this.

We have not had any 503 issues in github actions for a little while. I will report back if it occurs again.

**Comment by terencet-dev** [comment]
Are you still experiencing issues?

**Comment by rowanmoul** [comment]
I have only seen this once recently, and it was actually in Azure Pipelines (we are still transitioning some of our builds to GitHub). I could get the precise timestamp if that is helpful, but this doesn't seem to be happening meaningfully often for us anymore.

**Comment by samcarton** [comment]
This has also been resolved for us, thanks for the fix @terencet-dev @northtyphoon
